### ISSUE TITLE
Siri won’t open window covering [iOS15.4/WatchOS8.5/MacOS12.3]

### ISSUE THREAD

**Issue by mika1337** [homebridge/homebridge#3100]
### Current Situation

I developed my own homebridge platform plugin to interface with the window shades in my home.
Prior to iOS15.4/WatchOS8.5/MacOS12.3 I was able to open and close my shades asking Siri.
Now Siri tells me that it is not supported and won’t open/close my shades.
Apart from that i can still control my shades from the Home App.
My guess is that this is not related to Homebridge but Apple in iOS/watchOS/macOS.
I was wondering if anyone else is having the same issue or have any advice.

### Logs

```markdown
No log appears in homebridge when Siri refuses to open/close shades.
```

### Configuration

```json
{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "0E:28:D8:01:57:79",
        "port": 52003,
        "pin": "XXX-XX-XXX"
    },
    "accessories": [
        {
            "name": "Test DS",
            "stateful": false,
            "reverse": false,
            "time": 10000,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8100,
            "platform": "config"
        },
        {
            "name": "Test CS8P",
            "platform": "Chronosoft8PuppeteerPlatform",
            "address": "chronosoft8.local",
            "port": "12345"
        }
    ]
}
```

### Environment

- OS: Docker inside Debian Bullseye
- Software: Homebridge 1.4.0

### Process Supervisor

Docker (Mention image name in `Additional Context`)

### Additional Context

Docker image : oznu/homebridge:latest

**Comment by NorthernMan54** [comment]
@mika1337 But default the logging of the communications from Siri and the Home app is not enabled.  If you start homebridge with a command line like this

```
DEBUG=HAP-NodeJS:* homebridge
```

It will log these communications which may show why Siri does not like your window coverings.

**Comment by mrreview** [comment]
Same issue here and more people in same situtation, seems the problem is affecting home assistant users also

**Comment by mika1337** [comment]
> @mika1337 But default the logging of the communications from Siri and the Home app is not enabled. If you start homebridge with a command line like this
> 
> ```
> DEBUG=HAP-NodeJS:* homebridge
> ```
> 
> It will log these communications which may show why Siri does not like your window coverings.

Just tried to enable logging as suggested, nothing appears when I try to open/close my coverings. (I see logs for other working accessories).
So it seems that Siri is filtering on its own.

**Comment by mika1337** [comment]
A workaround is to ask Siri to set the covering to a define position as found here: https://www.reddit.com/r/HomeKit/comments/te7s4u/ios_154_siri_no_longer_understands_how_to_operate/

**Comment by jvmahon** [comment]
Fixed in iOS 15.4.1!

**Comment by mika1337** [comment]
Works again with iOS 15.4.1

**Comment by mika1337** [comment]
Reopening the issue since it still doesn't work on watchOS as mentioned here : https://github.com/home-assistant/core/issues/68247#issuecomment-1085723347
Didn't try macOS.

**Comment by dillonp23** [comment]
It seems like Siri will randomly act up for no apparent reason for me, but I usually have success setting up a Siri Shortcut as a workaround. Have you tried going that route?

**Comment by JohnWilliamson-1970** [comment]
It's fixed on iOS but not WatchOS - it's a complete pain

**Comment by mika1337** [comment]
Seems to be fixed in watchOS 8.6.
I managed to open my blinds with my watch this morning.

**Comment by JohnWilliamson-1970** [comment]
Thanks for the heads up @mika1337 I'm updating my Watch now and will give it a try.
